name: cleanup caches by a branch
on: delete
  
jobs:
  cleanup:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:      
      - name: Cleanup
        run: |
          gh extension install actions/gh-actions-cache
          
          echo "Fetching list of cache key"
          cacheKeysForPR=$(gh actions-cache list -R "${REPO}" -B "${BRANCH}" -L 100 | cut -f 1 )
          while test -n "${cacheKeysForPR}"
          do 
            ## Setting this to not fail the workflow while deleting cache keys. 
            set +e
            echo "Deleting caches..."
            for cacheKey in ${cacheKeysForPR}
            do
                gh actions-cache delete "${cacheKey}" -R "${REPO}" -B "${BRANCH}" --confirm
            done

            ## Setting this to fail the workflow while fetching cache keys. 
            set -e
            cacheKeysForPR=$(gh actions-cache list -R "${REPO}" -B "${BRANCH}" -L 100 | cut -f 1 )

          done
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.event.ref }}
