name: Build and test go application

on:
  push:
    branches-ignore: [ "main" ]
    paths:
      - '.github/workflows/devel.yml'
      - '**.py'
      - 'requirements.txt'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - 
      name: Checkout
      uses: actions/checkout@v4 # https://github.com/actions/checkout
    - 
      name: Set up Go
      uses: actions/setup-go@v4 # https://github.com/actions/setup-go
      with:
        go-version: '1.21'
        check-latest: true
    - 
      name: Build
      run: go build -v ./...
    - 
      name: Test
      run: go test -v ./...
